import { Expert } from './types';

const YT = 'https://www.youtube.com/shorts/49jpW2toHsM';

// 공용 운영시간 프리셋 (mock — 실데이터는 어드민/CSV로 입력)
const DAY = { weekday_start: '09:00', weekday_end: '18:00' };

export const MOCK_EXPERTS: Expert[] = [
  // ── 변호사 (lawyer) ──────────────────────────────────────────
  {
    id: 'lawyer-1',
    name: '김민준',
    vertical: 'lawyer',
    specialties: ['형사', '성범죄 무고', '고소·고발'],
    region: '서울 강남',
    phone: '010-1234-5678',
    experience_years: 15,
    bio: '검사 출신 형사전문 변호사. 경찰 조사 단계부터 1심까지 직접 동행합니다. 긴급 대응 전문.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: true, night_available: true,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'lawyer-2',
    name: '이수진',
    vertical: 'lawyer',
    specialties: ['이혼·가사', '위자료', '양육권'],
    region: '서울 서초',
    phone: '010-2345-6789',
    experience_years: 12,
    bio: '가사 전문 변호사. 이혼·양육권 분쟁 500건 이상 처리. 초기 상담부터 합의까지 동반.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'lawyer-3',
    name: '박성호',
    vertical: 'lawyer',
    specialties: ['사기·횡령', '채권 회수', '민사소송'],
    region: '서울 종로',
    phone: '010-3456-7890',
    experience_years: 18,
    bio: '사기 피해 특화. 피해액 회수율 72%. 빠른 가압류·가처분 조치.',
    youtube_url: YT,
    status: 'delayed',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-03T00:00:00Z',
  },

  // ── 노무사 (labor) ──────────────────────────────────────────
  {
    id: 'labor-1',
    name: '정다은',
    vertical: 'labor',
    specialties: ['부당해고', '해고예고수당', '원직복직'],
    region: '서울 마포',
    phone: '010-4567-8901',
    experience_years: 10,
    bio: '부당해고 전문 노무사. 노동위원회 심판 90% 승소율. 해고 통보 당일 대응 가능.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: true, night_available: false,
    is_active: true,
    created_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 'labor-2',
    name: '최재원',
    vertical: 'labor',
    specialties: ['임금체불', '퇴직금', '연장근로수당'],
    region: '경기 수원',
    phone: '010-5678-9012',
    experience_years: 8,
    bio: '임금 전문 노무사. 체불 임금 청구 평균 처리 기간 21일. 전국 온라인 상담 가능.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 'labor-3',
    name: '한지영',
    vertical: 'labor',
    specialties: ['직장 내 괴롭힘', '성희롱', '근로환경 개선'],
    region: '서울 강서',
    phone: '010-6789-0123',
    experience_years: 7,
    bio: '직장 내 괴롭힘·성희롱 신고 절차 전문. 고용노동부 진정 대리.',
    youtube_url: YT,
    status: 'unavailable',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-06T00:00:00Z',
  },

  // ── 손해사정사 (adjuster) ──────────────────────────────────
  {
    id: 'adjuster-1',
    name: '오준혁',
    vertical: 'adjuster',
    specialties: ['교통사고', '대물·대인 배상', '합의금 협상'],
    region: '서울 송파',
    phone: '010-7890-1234',
    experience_years: 14,
    bio: '보험사 출신 손해사정사. 합의금 평균 37% 상향. 사고 당일 현장 출동 가능.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: true, night_available: true,
    is_active: true,
    created_at: '2024-01-07T00:00:00Z',
  },
  {
    id: 'adjuster-2',
    name: '신예린',
    vertical: 'adjuster',
    specialties: ['산재', '업무상 재해', '산재 보험금'],
    region: '부산 해운대',
    phone: '010-8901-2345',
    experience_years: 9,
    bio: '산재 전문 손해사정사. 불승인 재심 청구 전담. 전국 출장 가능.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-08T00:00:00Z',
  },
  {
    id: 'adjuster-3',
    name: '윤태민',
    vertical: 'adjuster',
    specialties: ['화재보험', '재물손해', '보험금 분쟁'],
    region: '서울 강북',
    phone: '010-9012-3456',
    experience_years: 11,
    bio: '화재·재물 손해사정 전문. 보험사 저평가 보험금 재산정.',
    youtube_url: YT,
    status: 'delayed',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-09T00:00:00Z',
  },

  // ── 세무사 (tax) ──────────────────────────────────────────
  {
    id: 'tax-1',
    name: '강현우',
    vertical: 'tax',
    specialties: ['세무조사 대응', '국세청 소명', '불복 청구'],
    region: '서울 역삼',
    phone: '010-0123-4567',
    experience_years: 16,
    bio: '국세청 출신 세무사. 세무조사 통지 즉시 대응. 소명자료 작성·제출 전담.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'tax-2',
    name: '임소연',
    vertical: 'tax',
    specialties: ['상속세', '증여세', '절세 전략'],
    region: '서울 압구정',
    phone: '010-1122-3344',
    experience_years: 13,
    bio: '상속·증여 전문 세무사. 사전 플래닝으로 세부담 평균 28% 절감.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-11T00:00:00Z',
  },
  {
    id: 'tax-3',
    name: '서동현',
    vertical: 'tax',
    specialties: ['부가세', '종합소득세', '법인세'],
    region: '인천 연수',
    phone: '010-2233-4455',
    experience_years: 6,
    bio: '소규모 사업자 세무 전문. 부가세·소득세 신고 대행 및 기장 서비스.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: true, night_available: false,
    is_active: true,
    created_at: '2024-01-12T00:00:00Z',
  },

  // ── 의사 (doctor) ──────────────────────────────────────────
  {
    id: 'doctor-1',
    name: '문지훈',
    vertical: 'doctor',
    specialties: ['응급의학', '내과', '증상 상담'],
    region: '서울 신촌',
    phone: '010-3344-5566',
    experience_years: 12,
    bio: '응급의학과 전문의. 증상 설명만으로 긴급도 즉시 판단. 병원 선택·이동 경로 안내.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: true, night_available: true,
    is_active: true,
    created_at: '2024-01-13T00:00:00Z',
  },
  {
    id: 'doctor-2',
    name: '류아영',
    vertical: 'doctor',
    specialties: ['가정의학', '만성질환', '건강 상담'],
    region: '서울 목동',
    phone: '010-4455-6677',
    experience_years: 9,
    bio: '가정의학과 전문의. 복잡한 증상의 원인 정리 및 적절한 진료과 연결.',
    youtube_url: YT,
    status: 'available',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-14T00:00:00Z',
  },
  {
    id: 'doctor-3',
    name: '조민성',
    vertical: 'doctor',
    specialties: ['정신건강의학', '스트레스', '불안·우울'],
    region: '서울 마포',
    phone: '010-5566-7788',
    experience_years: 10,
    bio: '정신건강의학과 전문의. 직장 스트레스·번아웃·수면 장애 온라인 상담 전문.',
    youtube_url: YT,
    status: 'unavailable',
    ...DAY, weekend_available: false, night_available: false,
    is_active: true,
    created_at: '2024-01-15T00:00:00Z',
  },
];
